minVersion: 0.29.3
changelogPolicy: auto
targets:
  - name: maven
    mavenCliPath: scripts/mvnw
    mavenSettingsPath: scripts/settings.xml
    mavenRepoId: ossrh-staging-api
    mavenRepoUrl: https://ossrh-staging-api.centralsonatype.com/service/local/staging/deploy/maven2/
    android: false
  - name: github
  - name: registry
    sdks:
      maven:io.sentry:sentry-maven-plugin:
